spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/vitis_vision_db
    username: vitis_vision_user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

server:
  port: 8181

application:
  security:
    jwt:
      secret-key: 3063273f3276282c4a2f7d3f28593f6557707247672b35546e47547e66
      expiration: 86400000

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"