spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/vitis_vision_db
    username: vitis_vision_user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

server:
  port: 8181