version: '3.8'

name: vitis-vision

services:
  app:
    image: vvs:0.0.1
    container_name: sb-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      pg.db:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg.db/vitis_vision_db

  pg.db:
    image: postgres:14.7-alpine
    container_name: pg-db
    environment:
      POSTGRES_USER: vitis_vision_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "books_db" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - vitis_vision_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  pg.admin:
    image: dpage/pgadmin4:7
    container_name: pg-admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - vitis_vision_pg_data:/var/lib/pgadmin

volumes:
  vitis_vision_db_data:
  vitis_vision_pg_data: